# Generated by Django 4.2.2 on 2023-06-30 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_author_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='is_owner',
            field=models.BooleanField(default=False),
        ),
    ]
