# Generated by Django 4.2.2 on 2023-06-30 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_author_is_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='is_owner',
            field=models.BooleanField(default=False, unique=True),
        ),
    ]
