# Generated by Django 4.2.2 on 2023-07-06 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmessage',
            name='text',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
